name: Update Market Data

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default GitHub Actions bot

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas wget

      - name: Run market data update script
        run: python marketdata.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Securely reference the PAT
        run: |
          git add .
          git commit -m "Automated market data update - $(date)" || exit 0
          git push https://Abhiram907:${GH_PAT}@github.com/Abhiram907/Market_watch.git main
